<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Exercícios Capítulo 4 - Estimador de Kaplan Meier</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; } /* Alert */
code span.an { color: #008000; } /* Annotation */
code span.at { } /* Attribute */
code span.bu { } /* BuiltIn */
code span.cf { color: #0000ff; } /* ControlFlow */
code span.ch { color: #008080; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #008000; } /* Comment */
code span.cv { color: #008000; } /* CommentVar */
code span.do { color: #008000; } /* Documentation */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.im { } /* Import */
code span.in { color: #008000; } /* Information */
code span.kw { color: #0000ff; } /* Keyword */
code span.op { } /* Operator */
code span.ot { color: #ff4000; } /* Other */
code span.pp { color: #ff4000; } /* Preprocessor */
code span.sc { color: #008080; } /* SpecialChar */
code span.ss { color: #008080; } /* SpecialString */
code span.st { color: #008080; } /* String */
code span.va { } /* Variable */
code span.vs { color: #008080; } /* VerbatimString */
code span.wa { color: #008000; font-weight: bold; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Análise de sobrevivência</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="exercicio-cap-2.html">Exercícios Capítulo 2</a>
</li>
<li>
  <a href="exercicio-cap-3.html">Exercícios Capítulo 3</a>
</li>
<li>
  <a href="exercicio-cap-4.html">Exercícios Capítulo 4</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Exercícios Capítulo 4 - Estimador de Kaplan Meier</h1>

</div>


<div id="pacotes-e-opções" class="section level2">
<h2>Pacotes e opções</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw">library</span>(dplyr)</a>
<a class="sourceLine" id="cb1-2" title="2"><span class="kw">library</span>(survival)</a></code></pre></div>
</div>
<div id="exercícios" class="section level2">
<h2>Exercícios</h2>
<div id="q4_1" class="section level3">
<h3>4.1</h3>
<p>Considere os dados de tempo de aleitamento de 15 crianças, descrito no exercício 2.1.</p>
<pre><code>6 12 10 3 5 1 6 8 1 5 2 2 5 8 1</code></pre>
<ol style="list-style-type: lower-alpha">
<li>Complete a tabela Kaplan-Meier abaixo com esses dados</li>
</ol>
<p><img src="questao_4_1.png" /></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1">x =<span class="st"> </span><span class="kw">c</span>(6L, 12L, 10L, 3L, 5L, 1L, 6L, 8L, 1L, 5L, 2L, 2L, 5L, 8L, 1L)</a>
<a class="sourceLine" id="cb3-2" title="2"></a>
<a class="sourceLine" id="cb3-3" title="3">t =<span class="st"> </span><span class="kw">sort</span>(<span class="kw">unique</span>(x))</a>
<a class="sourceLine" id="cb3-4" title="4">inter =<span class="st"> </span><span class="kw">lead</span>(<span class="kw">cut</span>(<span class="kw">c</span>(<span class="dv">0</span>,t), <span class="dt">breaks =</span> <span class="kw">c</span>(<span class="dv">0</span>,t)))[<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(t)]</a>
<a class="sourceLine" id="cb3-5" title="5">Nt =<span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">table</span>(x))</a>
<a class="sourceLine" id="cb3-6" title="6">Rt =<span class="st"> </span><span class="kw">rev</span>(<span class="kw">cumsum</span>(<span class="kw">rev</span>(Nt)))</a>
<a class="sourceLine" id="cb3-7" title="7">Skm =<span class="st"> </span><span class="kw">cumprod</span>((Rt <span class="op">-</span><span class="st"> </span>Nt)<span class="op">/</span>Rt)</a>
<a class="sourceLine" id="cb3-8" title="8">Lambda =<span class="st"> </span><span class="op">-</span><span class="kw">log</span>(Skm)</a>
<a class="sourceLine" id="cb3-9" title="9"></a>
<a class="sourceLine" id="cb3-10" title="10">aleit &lt;-<span class="st"> </span><span class="kw">data.frame</span>(t, inter, Nt, Rt, Lambda, Skm)</a>
<a class="sourceLine" id="cb3-11" title="11"></a>
<a class="sourceLine" id="cb3-12" title="12">names &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;$t$&quot;</span>, <span class="st">&quot;Intervalo&quot;</span>, <span class="st">&quot;$N(t)$&quot;</span>, <span class="st">&quot;$R(t)$&quot;</span>,</a>
<a class="sourceLine" id="cb3-13" title="13">           <span class="st">&quot;$</span><span class="ch">\\</span><span class="st">hat{</span><span class="ch">\\</span><span class="st">Lambda}(t)$&quot;</span>, <span class="st">&quot;$</span><span class="ch">\\</span><span class="st">hat{S}_{km}(t)$&quot;</span>)</a>
<a class="sourceLine" id="cb3-14" title="14"></a>
<a class="sourceLine" id="cb3-15" title="15">knitr<span class="op">::</span><span class="kw">kable</span>(aleit, <span class="dt">digits =</span> <span class="dv">4</span>, <span class="dt">col.names =</span> names)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right"><span class="math inline">\(t\)</span></th>
<th align="left">Intervalo</th>
<th align="right"><span class="math inline">\(N(t)\)</span></th>
<th align="right"><span class="math inline">\(R(t)\)</span></th>
<th align="right"><span class="math inline">\(\hat{\Lambda}(t)\)</span></th>
<th align="right"><span class="math inline">\(\hat{S}_{km}(t)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">(0,1]</td>
<td align="right">3</td>
<td align="right">15</td>
<td align="right">0.2231</td>
<td align="right">0.8000</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">(1,2]</td>
<td align="right">2</td>
<td align="right">12</td>
<td align="right">0.4055</td>
<td align="right">0.6667</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">(2,3]</td>
<td align="right">1</td>
<td align="right">10</td>
<td align="right">0.5108</td>
<td align="right">0.6000</td>
</tr>
<tr class="even">
<td align="right">5</td>
<td align="left">(3,5]</td>
<td align="right">3</td>
<td align="right">9</td>
<td align="right">0.9163</td>
<td align="right">0.4000</td>
</tr>
<tr class="odd">
<td align="right">6</td>
<td align="left">(5,6]</td>
<td align="right">2</td>
<td align="right">6</td>
<td align="right">1.3218</td>
<td align="right">0.2667</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="left">(6,8]</td>
<td align="right">2</td>
<td align="right">4</td>
<td align="right">2.0149</td>
<td align="right">0.1333</td>
</tr>
<tr class="odd">
<td align="right">10</td>
<td align="left">(8,10]</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">2.7081</td>
<td align="right">0.0667</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="left">(10,12]</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">Inf</td>
<td align="right">0.0000</td>
</tr>
</tbody>
</table>
<ol start="2" style="list-style-type: lower-alpha">
<li>Desenhe a curva de Kaplan Meier correspondente aos dados.</li>
</ol>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1">y &lt;-<span class="st"> </span><span class="kw">Surv</span>(x, <span class="kw">rep</span>(<span class="dv">1</span>, <span class="kw">length</span>(x)))</a>
<a class="sourceLine" id="cb4-2" title="2">y_fit &lt;-<span class="st"> </span><span class="kw">survfit</span>(y <span class="op">~</span><span class="st"> </span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb4-3" title="3"><span class="kw">plot</span>(</a>
<a class="sourceLine" id="cb4-4" title="4">  y_fit,</a>
<a class="sourceLine" id="cb4-5" title="5">  <span class="dt">conf.int =</span> F,</a>
<a class="sourceLine" id="cb4-6" title="6">  <span class="dt">main =</span> <span class="st">&quot;Tempo de aleitamento&quot;</span>,</a>
<a class="sourceLine" id="cb4-7" title="7">  <span class="dt">xlab =</span> <span class="st">&quot;Meses&quot;</span>,</a>
<a class="sourceLine" id="cb4-8" title="8">  <span class="dt">ylab =</span> <span class="kw">expression</span>(<span class="kw">hat</span>(S)[km](t))</a>
<a class="sourceLine" id="cb4-9" title="9">)</a></code></pre></div>
<p><img src="exercicio-cap-4_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Qual a probabilidade de uma criança ser amamentada pelo menos até o sexto mês de vida?</li>
</ol>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="kw">plot</span>(</a>
<a class="sourceLine" id="cb5-2" title="2">  y_fit,</a>
<a class="sourceLine" id="cb5-3" title="3">  <span class="dt">conf.int =</span> F,</a>
<a class="sourceLine" id="cb5-4" title="4">  <span class="dt">main =</span> <span class="st">&quot;Tempo de aleitamento&quot;</span>,</a>
<a class="sourceLine" id="cb5-5" title="5">  <span class="dt">xlab =</span> <span class="st">&quot;Meses&quot;</span>,</a>
<a class="sourceLine" id="cb5-6" title="6">  <span class="dt">ylab =</span> <span class="kw">expression</span>(<span class="kw">hat</span>(S)[km](t))</a>
<a class="sourceLine" id="cb5-7" title="7">)</a>
<a class="sourceLine" id="cb5-8" title="8"><span class="kw">abline</span>(<span class="dt">h =</span> <span class="fl">0.2667</span>, <span class="dt">v =</span> <span class="dv">6</span>, <span class="dt">lty =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="exercicio-cap-4_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>A probabilidade é de <span class="math inline">\(S(6) = 0,2667\)</span>.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Qual a probabilidade de ser amamentada por mais de 3 meses?</li>
</ol>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" title="1"><span class="kw">plot</span>(</a>
<a class="sourceLine" id="cb6-2" title="2">  y_fit,</a>
<a class="sourceLine" id="cb6-3" title="3">  <span class="dt">conf.int =</span> F,</a>
<a class="sourceLine" id="cb6-4" title="4">  <span class="dt">main =</span> <span class="st">&quot;Tempo de aleitamento&quot;</span>,</a>
<a class="sourceLine" id="cb6-5" title="5">  <span class="dt">xlab =</span> <span class="st">&quot;Meses&quot;</span>,</a>
<a class="sourceLine" id="cb6-6" title="6">  <span class="dt">ylab =</span> <span class="kw">expression</span>(<span class="kw">hat</span>(S)[km](t))</a>
<a class="sourceLine" id="cb6-7" title="7">)</a>
<a class="sourceLine" id="cb6-8" title="8"><span class="kw">abline</span>(<span class="dt">h =</span> <span class="fl">0.6</span>, <span class="dt">v =</span> <span class="dv">3</span>, <span class="dt">lty =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="exercicio-cap-4_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>A probabilidade é de <span class="math inline">\(S(3) = 0,6\)</span>.</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Qual a probabilidade de ser amamentada por mais de 10 meses?</li>
</ol>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1"><span class="kw">plot</span>(</a>
<a class="sourceLine" id="cb7-2" title="2">  y_fit,</a>
<a class="sourceLine" id="cb7-3" title="3">  <span class="dt">conf.int =</span> F,</a>
<a class="sourceLine" id="cb7-4" title="4">  <span class="dt">main =</span> <span class="st">&quot;Tempo de aleitamento&quot;</span>,</a>
<a class="sourceLine" id="cb7-5" title="5">  <span class="dt">xlab =</span> <span class="st">&quot;Meses&quot;</span>,</a>
<a class="sourceLine" id="cb7-6" title="6">  <span class="dt">ylab =</span> <span class="kw">expression</span>(<span class="kw">hat</span>(S)[km](t))</a>
<a class="sourceLine" id="cb7-7" title="7">)</a>
<a class="sourceLine" id="cb7-8" title="8"><span class="kw">abline</span>(<span class="dt">h =</span> <span class="fl">0.0667</span>, <span class="dt">v =</span> <span class="dv">10</span>, <span class="dt">lty =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="exercicio-cap-4_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>A probabilidade é de <span class="math inline">\(S(10) = 0,0667\)</span>.</p>
<ol start="6" style="list-style-type: lower-alpha">
<li>Qual o tempo mediano de aleitamento?</li>
</ol>
<p>O tempo mediano de aleitamento é dado pela valor de <span class="math inline">\(S(t)\le 0,5\)</span>.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1"><span class="kw">plot</span>(</a>
<a class="sourceLine" id="cb8-2" title="2">  y_fit,</a>
<a class="sourceLine" id="cb8-3" title="3">  <span class="dt">conf.int =</span> F,</a>
<a class="sourceLine" id="cb8-4" title="4">  <span class="dt">main =</span> <span class="st">&quot;Tempo de aleitamento&quot;</span>,</a>
<a class="sourceLine" id="cb8-5" title="5">  <span class="dt">xlab =</span> <span class="st">&quot;Meses&quot;</span>,</a>
<a class="sourceLine" id="cb8-6" title="6">  <span class="dt">ylab =</span> <span class="kw">expression</span>(<span class="kw">hat</span>(S)[km](t))</a>
<a class="sourceLine" id="cb8-7" title="7">)</a>
<a class="sourceLine" id="cb8-8" title="8"><span class="kw">abline</span>(<span class="dt">h =</span> <span class="fl">0.5</span>, <span class="dt">v =</span> <span class="dv">5</span>, <span class="dt">lty =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="exercicio-cap-4_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>No caso, o valor mais próximo que satisfaz esta condição é <span class="math inline">\(t = 5\)</span>, para o qual o valor de <span class="math inline">\(S(t)\)</span> é <span class="math inline">\(0,4\)</span>. Ou seja: <span class="math display">\[\hat{S}_{km}(5) = 0,4\]</span></p>
</div>
<div id="section" class="section level3">
<h3>4.2</h3>
<p>Ainda com os dados do aleitamento construa a tabela de risco usando os estimadores Kaplan Meier e Nelson-Aalen.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1">t =<span class="st"> </span><span class="kw">sort</span>(<span class="kw">unique</span>(x))</a>
<a class="sourceLine" id="cb9-2" title="2">inter =<span class="st"> </span><span class="kw">lead</span>(<span class="kw">cut</span>(<span class="kw">c</span>(<span class="dv">0</span>,t), <span class="dt">breaks =</span> <span class="kw">c</span>(<span class="dv">0</span>,t)))[<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(t)]</a>
<a class="sourceLine" id="cb9-3" title="3">Nt =<span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">table</span>(x))</a>
<a class="sourceLine" id="cb9-4" title="4">Rt =<span class="st"> </span><span class="kw">rev</span>(<span class="kw">cumsum</span>(<span class="kw">rev</span>(Nt)))</a>
<a class="sourceLine" id="cb9-5" title="5">Skm =<span class="st"> </span><span class="kw">cumprod</span>((Rt <span class="op">-</span><span class="st"> </span>Nt)<span class="op">/</span>Rt)</a>
<a class="sourceLine" id="cb9-6" title="6">Lkm =<span class="st"> </span><span class="op">-</span><span class="kw">log</span>(Skm)</a>
<a class="sourceLine" id="cb9-7" title="7">Lna =<span class="st"> </span><span class="kw">cumsum</span>(Nt<span class="op">/</span>Rt)</a>
<a class="sourceLine" id="cb9-8" title="8"></a>
<a class="sourceLine" id="cb9-9" title="9">aleit_na &lt;-<span class="st"> </span><span class="kw">data.frame</span>(t, inter, Nt, Rt, Lkm, Lna)</a>
<a class="sourceLine" id="cb9-10" title="10"></a>
<a class="sourceLine" id="cb9-11" title="11">names &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;$t$&quot;</span>, <span class="st">&quot;Intervalo&quot;</span>, <span class="st">&quot;$N(t)$&quot;</span>, <span class="st">&quot;$R(t)$&quot;</span>,</a>
<a class="sourceLine" id="cb9-12" title="12">           <span class="st">&quot;$</span><span class="ch">\\</span><span class="st">hat{</span><span class="ch">\\</span><span class="st">Lambda}_{km}(t)$&quot;</span>, <span class="st">&quot;$</span><span class="ch">\\</span><span class="st">hat{</span><span class="ch">\\</span><span class="st">Lambda}_{na}(t)$&quot;</span>)</a>
<a class="sourceLine" id="cb9-13" title="13"></a>
<a class="sourceLine" id="cb9-14" title="14">knitr<span class="op">::</span><span class="kw">kable</span>(aleit_na, <span class="dt">digits =</span> <span class="dv">4</span>, <span class="dt">col.names =</span> names)</a></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right"><span class="math inline">\(t\)</span></th>
<th align="left">Intervalo</th>
<th align="right"><span class="math inline">\(N(t)\)</span></th>
<th align="right"><span class="math inline">\(R(t)\)</span></th>
<th align="right"><span class="math inline">\(\hat{\Lambda}_{km}(t)\)</span></th>
<th align="right"><span class="math inline">\(\hat{\Lambda}_{na}(t)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">(0,1]</td>
<td align="right">3</td>
<td align="right">15</td>
<td align="right">0.2231</td>
<td align="right">0.2000</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">(1,2]</td>
<td align="right">2</td>
<td align="right">12</td>
<td align="right">0.4055</td>
<td align="right">0.3667</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">(2,3]</td>
<td align="right">1</td>
<td align="right">10</td>
<td align="right">0.5108</td>
<td align="right">0.4667</td>
</tr>
<tr class="even">
<td align="right">5</td>
<td align="left">(3,5]</td>
<td align="right">3</td>
<td align="right">9</td>
<td align="right">0.9163</td>
<td align="right">0.8000</td>
</tr>
<tr class="odd">
<td align="right">6</td>
<td align="left">(5,6]</td>
<td align="right">2</td>
<td align="right">6</td>
<td align="right">1.3218</td>
<td align="right">1.1333</td>
</tr>
<tr class="even">
<td align="right">8</td>
<td align="left">(6,8]</td>
<td align="right">2</td>
<td align="right">4</td>
<td align="right">2.0149</td>
<td align="right">1.6333</td>
</tr>
<tr class="odd">
<td align="right">10</td>
<td align="left">(8,10]</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">2.7081</td>
<td align="right">2.1333</td>
</tr>
<tr class="even">
<td align="right">12</td>
<td align="left">(10,12]</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">Inf</td>
<td align="right">3.1333</td>
</tr>
</tbody>
</table>
</div>
<div id="section-1" class="section level3">
<h3>4.3</h3>
<p>Os dados completos de tempo de aleitamento (estudo fictício) estão presentes no arquivo <em>leite.txt</em>, Apêndice 12.4. Abra este banco de dados no R e:</p>
<ol style="list-style-type: lower-alpha">
<li>Construa a tabela Kaplan-Meier. Verifique qual o tempo mediano de aleitamento na saída do R.
<ul>
<li>Como não foi possível importar o arquivo <em>leite.txt</em>, construímos o banco “manualmente” <a href="#q4_1">acima</a>.</li>
</ul></li>
</ol>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" title="1">aleit_fit &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(x) <span class="op">~</span><span class="st"> </span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb10-2" title="2"><span class="kw">summary</span>(aleit_fit)</a></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(x) ~ 1)
## 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##     1     15       3   0.8000  0.1033       0.6212        1.000
##     2     12       2   0.6667  0.1217       0.4661        0.953
##     3     10       1   0.6000  0.1265       0.3969        0.907
##     5      9       3   0.4000  0.1265       0.2152        0.743
##     6      6       2   0.2667  0.1142       0.1152        0.617
##     8      4       2   0.1333  0.0878       0.0367        0.484
##    10      2       1   0.0667  0.0644       0.0100        0.443
##    12      1       1   0.0000     NaN           NA           NA</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>Construa a curva de sobrevivência do aleitamento indicando seu ponto mediano.</li>
</ol>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1"><span class="kw">plot</span>(</a>
<a class="sourceLine" id="cb12-2" title="2">  aleit_fit,</a>
<a class="sourceLine" id="cb12-3" title="3">  <span class="dt">conf.int =</span> F,</a>
<a class="sourceLine" id="cb12-4" title="4">  <span class="dt">main =</span> <span class="st">&quot;Tempo de aleitamento&quot;</span>,</a>
<a class="sourceLine" id="cb12-5" title="5">  <span class="dt">xlab =</span> <span class="st">&quot;Meses&quot;</span>,</a>
<a class="sourceLine" id="cb12-6" title="6">  <span class="dt">ylab =</span> <span class="kw">expression</span>(<span class="kw">hat</span>(S)[km](t))</a>
<a class="sourceLine" id="cb12-7" title="7">)</a>
<a class="sourceLine" id="cb12-8" title="8"></a>
<a class="sourceLine" id="cb12-9" title="9"><span class="kw">lines</span>(<span class="kw">list</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">0.5</span>,   <span class="dv">5</span>,    <span class="dv">5</span>),</a>
<a class="sourceLine" id="cb12-10" title="10">           <span class="dt">y =</span> <span class="kw">c</span>(<span class="fl">0.4</span>, <span class="fl">0.4</span>, <span class="fl">-0.5</span>)),</a>
<a class="sourceLine" id="cb12-11" title="11">      <span class="dt">lty =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb12-12" title="12"><span class="kw">points</span>(<span class="dv">5</span>, <span class="fl">0.4</span>, <span class="dt">pch =</span> <span class="dv">16</span>)</a>
<a class="sourceLine" id="cb12-13" title="13"></a>
<a class="sourceLine" id="cb12-14" title="14"><span class="kw">text</span>(<span class="dv">5</span>, <span class="fl">0.4</span>, <span class="st">&quot;Mediana&quot;</span>, <span class="dt">adj =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">0.05</span>, <span class="fl">-0.2</span>))</a></code></pre></div>
<p><img src="exercicio-cap-4_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Calcule as estimativas de Nelson-Aalen usando a função <code>coxph()</code>.</li>
</ol>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1">al_fit_na &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">coxph</span>(<span class="kw">Surv</span>(x) <span class="op">~</span><span class="st"> </span><span class="dv">1</span>))</a>
<a class="sourceLine" id="cb13-2" title="2">al_fit_na</a></code></pre></div>
<pre><code>## Call: survfit(formula = coxph(Surv(x) ~ 1))
## 
##       n  events  median 0.95LCL 0.95UCL 
##      15      15       5       2      10</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1"><span class="kw">summary</span>(al_fit_na)</a></code></pre></div>
<pre><code>## Call: survfit(formula = coxph(Surv(x) ~ 1))
## 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##     1     15       3   0.8065  0.1003      0.63208        1.000
##     2     12       2   0.6776  0.1187      0.48070        0.955
##     3     10       1   0.6131  0.1236      0.41291        0.910
##     5      9       3   0.4197  0.1252      0.23384        0.753
##     6      6       2   0.2909  0.1152      0.13384        0.632
##     8      4       2   0.1623  0.0933      0.05261        0.501
##    10      2       1   0.0984  0.0750      0.02212        0.438
##    12      1       1   0.0362  0.0455      0.00308        0.426</code></pre>
</div>
<div id="section-2" class="section level3">
<h3>4.4</h3>
<p>Em que situação se deve dar preferência as estimativas de Nelson-Aalen?</p>
<div class="line-block">     Para amostras maiores, os resultados das estimativas de Kaplan-Meier e Nelson-Aalen tendem a convergir, porém, para pequenas amostras (n<br />
     &lt; 100), Nelson-Aalen é mais indicado por ter propriedades estatísticas vantajosas, além de produzir estatísticas mais conservadoras,<br />
     especialmente no final do período.</div>
</div>
<div id="section-3" class="section level3">
<h3>4.5</h3>
<p>Suponha que os tempos de aleitamento de 60 bebês estejam agrupados em quatro comunidades diferentes:</p>
<pre><code>Comunidade 1: 6 12 10 3 5 1 6 8 1 5 2 2 5 8 1
Comunidade 2: 5 12 10 4 4 3 6 9 2 6 4 1 7 10 1
Comunidade 3: 13 14 20 3 5 1 8 15 2 5 3 2 6 15 1
Comunidade 4: 1 16 20 1 1 1 1 2 2 13 3 1 1 14 2</code></pre>
<div class="line-block">    Construímos o banco leite2 abaixo, manualmente.</div>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1">leite2 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">id =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">60</span>,</a>
<a class="sourceLine" id="cb18-2" title="2">           <span class="dt">tempo =</span> <span class="kw">c</span>(6L, 12L, 10L, 3L, 5L, 1L, 6L, 8L, 1L, 5L, 2L, 2L,</a>
<a class="sourceLine" id="cb18-3" title="3">                     5L, 8L, 1L, 5L, 12L, 10L, 4L, 4L, 3L, 6L, 9L, 2L,</a>
<a class="sourceLine" id="cb18-4" title="4">                     6L, 4L, 1L, 7L, 10L, 1L, 13L, 14L, 20L, 3L, 5L, 1L,</a>
<a class="sourceLine" id="cb18-5" title="5">                     8L, 15L, 2L, 5L, 3L, 2L, 6L, 15L, 1L, 1L, 16L, 20L,</a>
<a class="sourceLine" id="cb18-6" title="6">                     1L, 1L, 1L, 1L, 2L, 2L, 13L, 3L, 1L, 1L, 14L, 2L),</a>
<a class="sourceLine" id="cb18-7" title="7">           <span class="dt">status =</span> <span class="dv">1</span>,</a>
<a class="sourceLine" id="cb18-8" title="8">           <span class="dt">grupo =</span> <span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, <span class="dt">each =</span> <span class="dv">15</span>))</a>
<a class="sourceLine" id="cb18-9" title="9">leite2</a></code></pre></div>
<pre><code>##    id tempo status grupo
## 1   1     6      1     1
## 2   2    12      1     1
## 3   3    10      1     1
## 4   4     3      1     1
## 5   5     5      1     1
## 6   6     1      1     1
## 7   7     6      1     1
## 8   8     8      1     1
## 9   9     1      1     1
## 10 10     5      1     1
## 11 11     2      1     1
## 12 12     2      1     1
## 13 13     5      1     1
## 14 14     8      1     1
## 15 15     1      1     1
## 16 16     5      1     2
## 17 17    12      1     2
## 18 18    10      1     2
## 19 19     4      1     2
## 20 20     4      1     2
## 21 21     3      1     2
## 22 22     6      1     2
## 23 23     9      1     2
## 24 24     2      1     2
## 25 25     6      1     2
## 26 26     4      1     2
## 27 27     1      1     2
## 28 28     7      1     2
## 29 29    10      1     2
## 30 30     1      1     2
## 31 31    13      1     3
## 32 32    14      1     3
## 33 33    20      1     3
## 34 34     3      1     3
## 35 35     5      1     3
## 36 36     1      1     3
## 37 37     8      1     3
## 38 38    15      1     3
## 39 39     2      1     3
## 40 40     5      1     3
## 41 41     3      1     3
## 42 42     2      1     3
## 43 43     6      1     3
## 44 44    15      1     3
## 45 45     1      1     3
## 46 46     1      1     4
## 47 47    16      1     4
## 48 48    20      1     4
## 49 49     1      1     4
## 50 50     1      1     4
## 51 51     1      1     4
## 52 52     1      1     4
## 53 53     2      1     4
## 54 54     2      1     4
## 55 55    13      1     4
## 56 56     3      1     4
## 57 57     1      1     4
## 58 58     1      1     4
## 59 59    14      1     4
## 60 60     2      1     4</code></pre>
<ol style="list-style-type: lower-alpha">
<li>Ajuste um modelo de Kaplan-Meier estratificado por comunidade e compare o tempo mediano de aleitamento em cada comunidade.</li>
</ol>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1"><span class="kw">survfit</span>(<span class="kw">Surv</span>(tempo, status) <span class="op">~</span><span class="st"> </span>grupo, <span class="dt">data =</span> leite2)</a></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(tempo, status) ~ grupo, data = leite2)
## 
##          n events median 0.95LCL 0.95UCL
## grupo=1 15     15      5       2       8
## grupo=2 15     15      5       4      10
## grupo=3 15     15      5       3      15
## grupo=4 15     15      2       1      14</code></pre>
<p>O tempo mediano de sobrevivência estimado é similar nos primeiros 3 grupos, porém, é bastante inferior no grupo 4.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Desenhe, no mesmo gráfico, as curvas de Kaplan-Meier, estratificadas por grupo. Como se comporta a curva de sobrevivência das outras comunidades quando comparadas a comunidade 1?</li>
</ol>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" title="1"><span class="kw">plot</span>(<span class="kw">survfit</span>(<span class="kw">Surv</span>(tempo, status) <span class="op">~</span><span class="st"> </span>grupo, <span class="dt">data =</span> leite2),</a>
<a class="sourceLine" id="cb22-2" title="2">     <span class="dt">col =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, <span class="dt">lty =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>)</a>
<a class="sourceLine" id="cb22-3" title="3"><span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="kw">c</span>(<span class="st">&quot;Com. 1&quot;</span>, <span class="st">&quot;Com. 2&quot;</span>, <span class="st">&quot;Com. 3&quot;</span>, <span class="st">&quot;Com. 4&quot;</span>), <span class="dt">fill =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>)</a></code></pre></div>
<p><img src="exercicio-cap-4_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<div class="line-block">     A comunidade 2 tem uma sobrevivência parecida com a 1, estimativas levemente melhores em alguns pontos.</div>
<div class="line-block">     A comunidade 3 tem uma sobrevivência parecida com a comunidade 1 no inicio do período, mas para o final do período, tem uma sobrevivência bem melhor.</div>
<div class="line-block">     A comunidade 4 tem uma sobrevivência pior que a 1 no início do período, mas no final do período, apresenta uma sobrevivência maior e comparável a comunidade 3.</div>
<ol start="3" style="list-style-type: lower-alpha">
<li>Use os testes log-rank e Peto para a variável <code>grupo</code>. Analise as funções de sobrevivência das quatro comunidades. A que conclusões você chega com esta análise? Existe diferença entre as comunidades quanto ao tempo de aleitamento?</li>
</ol>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" title="1"><span class="kw">survdiff</span>(<span class="kw">Surv</span>(tempo, status) <span class="op">~</span><span class="st"> </span>grupo, <span class="dt">data =</span> leite2)</a></code></pre></div>
<pre><code>## Call:
## survdiff(formula = Surv(tempo, status) ~ grupo, data = leite2)
## 
##          N Observed Expected (O-E)^2/E (O-E)^2/V
## grupo=1 15       15     12.4    0.5489    0.8735
## grupo=2 15       15     13.4    0.1862    0.3028
## grupo=3 15       15     19.7    1.1220    2.1534
## grupo=4 15       15     14.5    0.0182    0.0323
## 
##  Chisq= 2.5  on 3 degrees of freedom, p= 0.5</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1"><span class="kw">survdiff</span>(<span class="kw">Surv</span>(tempo, status) <span class="op">~</span><span class="st"> </span>grupo, <span class="dt">rho =</span> <span class="dv">1</span>, <span class="dt">data =</span> leite2)</a></code></pre></div>
<pre><code>## Call:
## survdiff(formula = Surv(tempo, status) ~ grupo, data = leite2, 
##     rho = 1)
## 
##          N Observed Expected (O-E)^2/E (O-E)^2/V
## grupo=1 15     8.48     8.22   0.00865    0.0187
## grupo=2 15     7.57     8.70   0.14764    0.3287
## grupo=3 15     6.97     9.43   0.64499    1.5446
## grupo=4 15    10.28     6.95   1.59872    3.3897
## 
##  Chisq= 4.1  on 3 degrees of freedom, p= 0.3</code></pre>
<p>Em ambos os casos observamos diferenças entre os valores observados e esperados nos grupos, porém, os p-valores são muito altos (0.5 e 0.3), o que sugere que os resultados podem ser resultado de variações amostrais e não necessariamente de diferenças entre as comunidades. Então, as diferenças entre os grupos não são estatisticamente significativas.</p>
</div>
<div id="section-4" class="section level3">
<h3>4.6</h3>
<p>O banco de dados <code>ipec.csv</code> contém os dados de uma coorte de pacientes com Aids atendidos no Ipec e descritos no apêndice 12.4. Para este estudo foi definido, como tempo de sobrevivência, o tempo entre o diagnóstico de Aids (critério CDC-1993) e o óbito.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" title="1"><span class="co"># Leitura-limpeza do banco ipec.csv</span></a>
<a class="sourceLine" id="cb27-2" title="2">ipec &lt;-<span class="st"> </span><span class="kw">read.csv2</span>(<span class="st">&quot;ipec.csv&quot;</span>)</a>
<a class="sourceLine" id="cb27-3" title="3"></a>
<a class="sourceLine" id="cb27-4" title="4">ipec<span class="op">$</span>anotrat[ipec<span class="op">$</span>anotrat <span class="op">==</span><span class="st"> </span><span class="dv">9</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></a>
<a class="sourceLine" id="cb27-5" title="5">ipec<span class="op">$</span>obito[ipec<span class="op">$</span>obito <span class="op">==</span><span class="st"> &quot;I&quot;</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></a>
<a class="sourceLine" id="cb27-6" title="6"></a>
<a class="sourceLine" id="cb27-7" title="7">ipec<span class="op">$</span>escola &lt;-<span class="st"> </span><span class="kw">factor</span>(</a>
<a class="sourceLine" id="cb27-8" title="8">  ipec<span class="op">$</span>escola,</a>
<a class="sourceLine" id="cb27-9" title="9">  <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;sem&quot;</span>, <span class="st">&quot;fundam&quot;</span>, <span class="st">&quot;medio&quot;</span>, <span class="st">&quot;sup&quot;</span>)</a>
<a class="sourceLine" id="cb27-10" title="10">)</a>
<a class="sourceLine" id="cb27-11" title="11"></a>
<a class="sourceLine" id="cb27-12" title="12">ipec<span class="op">$</span>risco &lt;-<span class="st"> </span><span class="kw">factor</span>(</a>
<a class="sourceLine" id="cb27-13" title="13">  ipec<span class="op">$</span>risco,</a>
<a class="sourceLine" id="cb27-14" title="14">  <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Homo&quot;</span>, <span class="st">&quot;UDI&quot;</span>, <span class="st">&quot;Transf&quot;</span>, <span class="st">&quot;Cont hetero&quot;</span>, <span class="st">&quot;Mut parc&quot;</span>, <span class="st">&quot;2 fat&quot;</span>)</a>
<a class="sourceLine" id="cb27-15" title="15">)</a>
<a class="sourceLine" id="cb27-16" title="16"></a>
<a class="sourceLine" id="cb27-17" title="17">ipec<span class="op">$</span>acompan &lt;-<span class="st"> </span><span class="kw">factor</span>(</a>
<a class="sourceLine" id="cb27-18" title="18">  ipec<span class="op">$</span>acompan,</a>
<a class="sourceLine" id="cb27-19" title="19">  <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Amb&quot;</span>, <span class="st">&quot;Int.Post&quot;</span>, <span class="st">&quot;Int.Imed&quot;</span>)</a>
<a class="sourceLine" id="cb27-20" title="20">)</a>
<a class="sourceLine" id="cb27-21" title="21"></a>
<a class="sourceLine" id="cb27-22" title="22">ipec<span class="op">$</span>anotrat &lt;-<span class="st"> </span><span class="kw">factor</span>(ipec<span class="op">$</span>anotrat)</a>
<a class="sourceLine" id="cb27-23" title="23"></a>
<a class="sourceLine" id="cb27-24" title="24">ipec<span class="op">$</span>tratam &lt;-<span class="st"> </span><span class="kw">factor</span>(</a>
<a class="sourceLine" id="cb27-25" title="25">  ipec<span class="op">$</span>tratam,</a>
<a class="sourceLine" id="cb27-26" title="26">  <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Nenhum&quot;</span>, <span class="st">&quot;Mono&quot;</span>, <span class="st">&quot;Combinada&quot;</span>, <span class="st">&quot;Potente&quot;</span>)</a>
<a class="sourceLine" id="cb27-27" title="27">)</a>
<a class="sourceLine" id="cb27-28" title="28"></a>
<a class="sourceLine" id="cb27-29" title="29">ipec<span class="op">$</span>doenca &lt;-<span class="st"> </span><span class="kw">factor</span>(</a>
<a class="sourceLine" id="cb27-30" title="30">  ipec<span class="op">$</span>doenca,</a>
<a class="sourceLine" id="cb27-31" title="31">  <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;PCP&quot;</span>, <span class="st">&quot;TB pulm&quot;</span>, <span class="st">&quot;TB diss&quot;</span>, <span class="st">&quot;Toxo&quot;</span>, <span class="st">&quot;SK&quot;</span>,</a>
<a class="sourceLine" id="cb27-32" title="32">             <span class="st">&quot;Outra&quot;</span>, <span class="st">&quot;Cand&quot;</span>, <span class="st">&quot;Herpes&quot;</span>, <span class="st">&quot;Duas&quot;</span>, <span class="st">&quot;Def CD4&quot;</span>)</a>
<a class="sourceLine" id="cb27-33" title="33">  )</a>
<a class="sourceLine" id="cb27-34" title="34"></a>
<a class="sourceLine" id="cb27-35" title="35">ipec<span class="op">$</span>propcp &lt;-<span class="st"> </span><span class="kw">factor</span>(</a>
<a class="sourceLine" id="cb27-36" title="36">  ipec<span class="op">$</span>propcp,</a>
<a class="sourceLine" id="cb27-37" title="37">  <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Sem&quot;</span>, <span class="st">&quot;Prim&quot;</span>, <span class="st">&quot;Secund&quot;</span>, <span class="st">&quot;Ambas&quot;</span>))</a></code></pre></div>
<ol style="list-style-type: lower-alpha">
<li>Amplie a análise exploratória desses dados usando o R:
<ol style="list-style-type: decimal">
<li>Qual é a idade média desses pacientes?<br />
</li>
<li>Qual a razão homens:mulheres nessa coorte?</li>
<li>Quantos receberam tratamento?</li>
<li>Quantos foram a óbito e quantos foram censurados?</li>
<li>Os óbitos e as censuras se concentraram no final do estudo ou ocorreram durante todo o período?</li>
<li>Qual o tempo de sobrevivência mediano?</li>
</ol></li>
<li>Existe diferença entre homens e mulheres quanto ao tempo de sobrevivência pós-diagnóstico de Aids?</li>
<li>Compare homens e mulheres segundo tempos de sobrevivência mediano e percentis 75 e 90.</li>
<li>Existe diferença na sobrevivência dos pacientes submetidos aos diferentes tipos de tratamento (variável <code>tratam</code>)?</li>
<li>Existe diferença na sobrevivência de pacientes com diferentes graus de escolaridade?</li>
<li>Faça os gráficos de sobrevivência e risco e aplique os testes log-rank e Peto.</li>
</ol>
<div id="análise-exploratória" class="section level4">
<h4>Análise exploratória</h4>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" title="1"><span class="co"># Idade média dos pacientes</span></a>
<a class="sourceLine" id="cb28-2" title="2"><span class="kw">mean</span>(ipec<span class="op">$</span>idade)</a></code></pre></div>
<pre><code>## [1] 36.55</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" title="1"><span class="co"># Razão entre homens e mulheres</span></a>
<a class="sourceLine" id="cb30-2" title="2">x &lt;-<span class="st"> </span><span class="kw">table</span>(ipec<span class="op">$</span>sexo)</a>
<a class="sourceLine" id="cb30-3" title="3"><span class="kw">as.numeric</span>(x[<span class="dv">2</span>]<span class="op">/</span>x[<span class="dv">1</span>])</a></code></pre></div>
<pre><code>## [1] 2.939</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1"><span class="co"># Quantos receberam tratamento?</span></a>
<a class="sourceLine" id="cb32-2" title="2">x &lt;-<span class="st"> </span><span class="kw">table</span>(ipec<span class="op">$</span>tratam)</a>
<a class="sourceLine" id="cb32-3" title="3"><span class="kw">sum</span>(x[<span class="dv">2</span><span class="op">:</span><span class="dv">4</span>])</a></code></pre></div>
<pre><code>## [1] 149</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" title="1"><span class="co"># Nº de óbitos e censuras</span></a>
<a class="sourceLine" id="cb34-2" title="2">x &lt;-<span class="st"> </span><span class="kw">table</span>(ipec<span class="op">$</span>status)</a>
<a class="sourceLine" id="cb34-3" title="3"><span class="kw">paste0</span>(x[<span class="dv">1</span>], <span class="st">&quot; foram censurados.&quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;103 foram censurados.&quot;</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" title="1"><span class="kw">paste0</span>(x[<span class="dv">2</span>], <span class="st">&quot; foram a óbito.&quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;90 foram a óbito.&quot;</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" title="1"><span class="co"># Dispersão temporal de óbitos e censuras</span></a>
<a class="sourceLine" id="cb38-2" title="2"><span class="kw">hist</span>(ipec<span class="op">$</span>tempo[ipec<span class="op">$</span>status <span class="op">==</span><span class="st"> </span><span class="dv">1</span>], <span class="dt">main =</span> <span class="st">&quot;Óbitos&quot;</span>)</a></code></pre></div>
<p><img src="exercicio-cap-4_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" title="1"><span class="kw">hist</span>(ipec<span class="op">$</span>tempo[ipec<span class="op">$</span>status <span class="op">==</span><span class="st"> </span><span class="dv">0</span>], <span class="dt">main =</span> <span class="st">&quot;Censuras&quot;</span>)</a></code></pre></div>
<p><img src="exercicio-cap-4_files/figure-html/unnamed-chunk-14-2.png" width="672" /></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" title="1"><span class="co"># Os óbitos concentraram-se principalmente no início do período, enquanto as censuras se distribuíram mais ao longo do período de estudo.</span></a>
<a class="sourceLine" id="cb40-2" title="2"></a>
<a class="sourceLine" id="cb40-3" title="3"><span class="co"># Tempo de sobrevivência mediano </span></a>
<a class="sourceLine" id="cb40-4" title="4">km &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(tempo, status) <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> ipec)</a>
<a class="sourceLine" id="cb40-5" title="5">km<span class="op">$</span>surv[km<span class="op">$</span>surv <span class="op">&lt;=</span><span class="st"> </span><span class="fl">0.5</span>][<span class="dv">1</span>]</a></code></pre></div>
<pre><code>## [1] 0.4955</code></pre>
</div>
<div id="diferenças-entre-homens-e-mulheres" class="section level4">
<h4>Diferenças entre homens e mulheres</h4>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" title="1">sexo &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(tempo, status) <span class="op">~</span><span class="st"> </span>sexo, <span class="dt">data =</span> ipec)</a>
<a class="sourceLine" id="cb42-2" title="2"><span class="kw">plot</span>(</a>
<a class="sourceLine" id="cb42-3" title="3">  sexo,</a>
<a class="sourceLine" id="cb42-4" title="4">  <span class="dt">col =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>,</a>
<a class="sourceLine" id="cb42-5" title="5">  <span class="dt">conf.int =</span> T,</a>
<a class="sourceLine" id="cb42-6" title="6">  <span class="dt">main =</span> <span class="st">&quot;Sobrevivência por sexo&quot;</span>,</a>
<a class="sourceLine" id="cb42-7" title="7">  <span class="dt">xlab =</span> <span class="st">&quot;Dias&quot;</span>,</a>
<a class="sourceLine" id="cb42-8" title="8">  <span class="dt">ylab =</span> <span class="kw">expression</span>(<span class="kw">S</span>(t))</a>
<a class="sourceLine" id="cb42-9" title="9">)</a>
<a class="sourceLine" id="cb42-10" title="10"><span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="dt">legend =</span> <span class="kw">levels</span>(ipec<span class="op">$</span>sexo), <span class="dt">fill =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>)</a></code></pre></div>
<p><img src="exercicio-cap-4_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" title="1"><span class="kw">plot</span>(</a>
<a class="sourceLine" id="cb43-2" title="2">  sexo,</a>
<a class="sourceLine" id="cb43-3" title="3">  <span class="dt">col =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>,</a>
<a class="sourceLine" id="cb43-4" title="4">  <span class="dt">conf.int =</span> F,</a>
<a class="sourceLine" id="cb43-5" title="5">  <span class="dt">fun =</span> <span class="st">&quot;cumhaz&quot;</span>,</a>
<a class="sourceLine" id="cb43-6" title="6">  <span class="dt">main =</span> <span class="st">&quot;Risco por sexo&quot;</span>,</a>
<a class="sourceLine" id="cb43-7" title="7">  <span class="dt">xlab =</span> <span class="st">&quot;Dias&quot;</span>,</a>
<a class="sourceLine" id="cb43-8" title="8">  <span class="dt">ylab =</span> <span class="kw">expression</span>(<span class="kw">S</span>(t))</a>
<a class="sourceLine" id="cb43-9" title="9">)</a>
<a class="sourceLine" id="cb43-10" title="10"><span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="dt">legend =</span> <span class="kw">levels</span>(ipec<span class="op">$</span>sexo), <span class="dt">fill =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>)</a></code></pre></div>
<p><img src="exercicio-cap-4_files/figure-html/unnamed-chunk-15-2.png" width="672" /></p>
<p>Há uma diferença expressiva na sobrevivência de homens e mulheres, algo que pode ser constatado na representação gráfica estratificada do Kaplan-Meier, porém, como há bastante sobreposição nos intervalos de confiança, executamos os testes de significância log-rank e Peto. Quando observamos a função de risco, vemos o mesmo padrão, embora no início do acompanhamento as curvas estejam muito próximas, a curva de risco das mulheres cresce mais lentamente a partir do 500º dia.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" title="1">sx_logr &lt;-<span class="st"> </span><span class="kw">survdiff</span>(<span class="kw">Surv</span>(tempo, status) <span class="op">~</span><span class="st"> </span>sexo, <span class="dt">data =</span> ipec)</a>
<a class="sourceLine" id="cb44-2" title="2">sx_peto &lt;-<span class="st"> </span><span class="kw">survdiff</span>(<span class="kw">Surv</span>(tempo, status) <span class="op">~</span><span class="st"> </span>sexo, <span class="dt">data =</span> ipec, <span class="dt">rho =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb44-3" title="3">sx_logr</a></code></pre></div>
<pre><code>## Call:
## survdiff(formula = Surv(tempo, status) ~ sexo, data = ipec)
## 
##          N Observed Expected (O-E)^2/E (O-E)^2/V
## sexo=F  49       16     24.5      2.93      4.03
## sexo=M 144       74     65.5      1.09      4.03
## 
##  Chisq= 4  on 1 degrees of freedom, p= 0.04</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1">sx_peto</a></code></pre></div>
<pre><code>## Call:
## survdiff(formula = Surv(tempo, status) ~ sexo, data = ipec, rho = 1)
## 
##          N Observed Expected (O-E)^2/E (O-E)^2/V
## sexo=F  49     12.1     18.2     2.011      3.54
## sexo=M 144     55.1     49.0     0.746      3.54
## 
##  Chisq= 3.5  on 1 degrees of freedom, p= 0.06</code></pre>
<p>Dentro de um intervalo de confiança de 0.05, o teste log-rank considerou as diferenças estatisticamente significantes, mas o teste de Peto não considerou significativa as diferenças (<span class="math inline">\(p = 0.06\)</span>). Considerando a importância da variável sexo nos desfechos de saúde, faz sentido considerar que o resultado é estatisticamente significativo apesar do resultado do teste Peto.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" title="1"><span class="kw">quantile</span>(sexo, <span class="dt">probs =</span> <span class="kw">c</span>(<span class="fl">0.1</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>))</a></code></pre></div>
<pre><code>## $quantile
##         10  25   50
## sexo=F 151 854   NA
## sexo=M 108 397 1116
## 
## $lower
##         10  25   50
## sexo=F 134 235 1371
## sexo=M  52 259  887
## 
## $upper
##         10  25   50
## sexo=F 721  NA   NA
## sexo=M 194 631 1563</code></pre>
<p>O valor da sobrevivência mediana dos homens é de 1116 dias [887, 1563], enquanto para as mulheres, não foi possível calcular este percentil, já que o estudo foi encerrado antes que a função de sobrevivência atingisse 0.5, mas o intervalo de confiança inferior foi de 1371 dias.</p>
<p>O valor do percentil 0.75 para os homens foi de 397 dias [259, 631], enquanto para as mulheres foi de 854 [235, <span class="math inline">\(\infty\)</span>]. Já o percentil 0.9 para os homens foi de 108 dias [52, 194], enquanto as mulheres atingiram este marca em 151 dias [134, 721].</p>
<p>Tanto analisando as estimativas pontuais quanto os intervalos de confiança, fica claro que as mulheres tem uma sobrevivência significativamente maior que os homens.</p>
</div>
<div id="diferenças-de-acordo-com-o-tratamento" class="section level4">
<h4>Diferenças de acordo com o tratamento</h4>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" title="1">tratam &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(tempo, status) <span class="op">~</span><span class="st"> </span>tratam, <span class="dt">data =</span> ipec)</a>
<a class="sourceLine" id="cb50-2" title="2"></a>
<a class="sourceLine" id="cb50-3" title="3"><span class="kw">plot</span>(</a>
<a class="sourceLine" id="cb50-4" title="4">  tratam,</a>
<a class="sourceLine" id="cb50-5" title="5">  <span class="dt">col =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,</a>
<a class="sourceLine" id="cb50-6" title="6">  <span class="dt">conf.int =</span> F,</a>
<a class="sourceLine" id="cb50-7" title="7">  <span class="dt">main =</span> <span class="st">&quot;Sobrevivência por tratamento&quot;</span>,</a>
<a class="sourceLine" id="cb50-8" title="8">  <span class="dt">xlab =</span> <span class="st">&quot;Dias&quot;</span>,</a>
<a class="sourceLine" id="cb50-9" title="9">  <span class="dt">ylab =</span> <span class="kw">expression</span>(<span class="kw">S</span>(t))</a>
<a class="sourceLine" id="cb50-10" title="10">)</a>
<a class="sourceLine" id="cb50-11" title="11"><span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="dt">legend =</span> <span class="kw">levels</span>(ipec<span class="op">$</span>tratam), <span class="dt">fill =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>)</a></code></pre></div>
<p><img src="exercicio-cap-4_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1"><span class="kw">plot</span>(</a>
<a class="sourceLine" id="cb51-2" title="2">  tratam,</a>
<a class="sourceLine" id="cb51-3" title="3">  <span class="dt">col =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,</a>
<a class="sourceLine" id="cb51-4" title="4">  <span class="dt">conf.int =</span> F,</a>
<a class="sourceLine" id="cb51-5" title="5">  <span class="dt">fun =</span> <span class="st">&quot;cumhaz&quot;</span>,</a>
<a class="sourceLine" id="cb51-6" title="6">  <span class="dt">main =</span> <span class="st">&quot;Risco por tratamento&quot;</span>,</a>
<a class="sourceLine" id="cb51-7" title="7">  <span class="dt">xlab =</span> <span class="st">&quot;Dias&quot;</span>,</a>
<a class="sourceLine" id="cb51-8" title="8">  <span class="dt">ylab =</span> <span class="kw">expression</span>(<span class="kw">S</span>(t))</a>
<a class="sourceLine" id="cb51-9" title="9">)</a>
<a class="sourceLine" id="cb51-10" title="10"><span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="dt">legend =</span> <span class="kw">levels</span>(ipec<span class="op">$</span>tratam), <span class="dt">fill =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>)</a></code></pre></div>
<p><img src="exercicio-cap-4_files/figure-html/unnamed-chunk-18-2.png" width="672" /></p>
<p>Há uma diferença considerável entre as sobrevivências de pacientes de acordo com o tratamento recebido. Os pacientes que não receberam nenhum tratamento têm curva de sobrevivência claramente inferior aos que receberam o tratamento mono, enquanto os pacientes que receberam a combinada e potente sobreviveram ainda mais. A função de risco explicita ainda mais a questão quando observamos o agrupamento das curvas dos pacientes tratados em relação aqueles que não receberam tratamento.</p>
<p>Podemos realizar os testes de significância estatística para nos certificar de que não se trata de resultado causado por variações na amostra.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" title="1">tto_lr &lt;-<span class="st"> </span><span class="kw">survdiff</span>(<span class="kw">Surv</span>(tempo, status) <span class="op">~</span><span class="st"> </span>tratam, <span class="dt">data =</span> ipec)</a>
<a class="sourceLine" id="cb52-2" title="2">tto_pt &lt;-<span class="st"> </span><span class="kw">survdiff</span>(<span class="kw">Surv</span>(tempo, status) <span class="op">~</span><span class="st"> </span>tratam, <span class="dt">data =</span> ipec, <span class="dt">rho =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb52-3" title="3">tto_lr</a></code></pre></div>
<pre><code>## Call:
## survdiff(formula = Surv(tempo, status) ~ tratam, data = ipec)
## 
##                    N Observed Expected (O-E)^2/E (O-E)^2/V
## tratam=Nenhum     44       32     9.51    53.229    61.560
## tratam=Mono      100       51    54.73     0.254     0.659
## tratam=Combinada  35        6    20.27    10.050    13.049
## tratam=Potente    14        1     5.49     3.674     3.950
## 
##  Chisq= 69  on 3 degrees of freedom, p= 7e-15</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" title="1">tto_pt</a></code></pre></div>
<pre><code>## Call:
## survdiff(formula = Surv(tempo, status) ~ tratam, data = ipec, 
##     rho = 1)
## 
##                    N Observed Expected (O-E)^2/E (O-E)^2/V
## tratam=Nenhum     44    27.03     7.81    47.230     65.78
## tratam=Mono      100    35.30    40.06     0.565      1.80
## tratam=Combinada  35     3.89    14.98     8.206     13.70
## tratam=Potente    14     1.00     4.37     2.597      3.43
## 
##  Chisq= 72.2  on 3 degrees of freedom, p= 1e-15</code></pre>
<p>Os testes demonstram que a significância estatística é fortíssima (<span class="math inline">\(p &lt; 0,000001\)</span>) e que os resultados são precisos. Ou seja, a hipótese nula encontra-se plenamente rejeitada e a sujeição ao tratamento apresenta forte correlação com a sobrevivência.</p>
<p>De fato, se verificamos os quantis da sobrevivência como no caso anterior,</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" title="1"><span class="kw">quantile</span>(tratam, <span class="dt">probs =</span> <span class="kw">c</span>(<span class="fl">0.1</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>))</a></code></pre></div>
<pre><code>## $quantile
##                   10   25   50
## tratam=Nenhum     40  116  173
## tratam=Mono      254  631 1226
## tratam=Combinada 775 2898 2898
## tratam=Potente    NA   NA   NA
## 
## $lower
##                   10  25   50
## tratam=Nenhum     29  54  151
## tratam=Mono      145 418  967
## tratam=Combinada 419 944 2898
## tratam=Potente    16  NA   NA
## 
## $upper
##                   10  25  50
## tratam=Nenhum    116 158 516
## tratam=Mono      418 892  NA
## tratam=Combinada  NA  NA  NA
## tratam=Potente    NA  NA  NA</code></pre>
<p>Notamos que os tratamentos melhoram a sobrevivência em todos os estágios, com os tratamentos “combinado” e “potente” sequer apresentando intervalos superiores. Na verdade, o tratamento “potente” nem chegou ao quantil 10%.</p>
</div>
<div id="diferenças-de-acordo-com-a-escolaridade" class="section level4">
<h4>Diferenças de acordo com a escolaridade</h4>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" title="1">escola &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(tempo, status) <span class="op">~</span><span class="st"> </span>escola, <span class="dt">data =</span> ipec)</a>
<a class="sourceLine" id="cb58-2" title="2"></a>
<a class="sourceLine" id="cb58-3" title="3"><span class="kw">plot</span>(</a>
<a class="sourceLine" id="cb58-4" title="4">  escola,</a>
<a class="sourceLine" id="cb58-5" title="5">  <span class="dt">col =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,</a>
<a class="sourceLine" id="cb58-6" title="6">  <span class="dt">conf.int =</span> F,</a>
<a class="sourceLine" id="cb58-7" title="7">  <span class="dt">main =</span> <span class="st">&quot;Sobrevivência por escolaridade&quot;</span>,</a>
<a class="sourceLine" id="cb58-8" title="8">  <span class="dt">xlab =</span> <span class="st">&quot;Dias&quot;</span>,</a>
<a class="sourceLine" id="cb58-9" title="9">  <span class="dt">ylab =</span> <span class="kw">expression</span>(<span class="kw">S</span>(t))</a>
<a class="sourceLine" id="cb58-10" title="10">)</a>
<a class="sourceLine" id="cb58-11" title="11"><span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="dt">legend =</span> <span class="kw">levels</span>(ipec<span class="op">$</span>escola), <span class="dt">fill =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>)</a></code></pre></div>
<p><img src="exercicio-cap-4_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1"><span class="kw">plot</span>(</a>
<a class="sourceLine" id="cb59-2" title="2">  escola,</a>
<a class="sourceLine" id="cb59-3" title="3">  <span class="dt">col =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>,</a>
<a class="sourceLine" id="cb59-4" title="4">  <span class="dt">conf.int =</span> F,</a>
<a class="sourceLine" id="cb59-5" title="5">  <span class="dt">fun =</span> <span class="st">&quot;cumhaz&quot;</span>,</a>
<a class="sourceLine" id="cb59-6" title="6">  <span class="dt">main =</span> <span class="st">&quot;Risco por escolaridade&quot;</span>,</a>
<a class="sourceLine" id="cb59-7" title="7">  <span class="dt">xlab =</span> <span class="st">&quot;Dias&quot;</span>,</a>
<a class="sourceLine" id="cb59-8" title="8">  <span class="dt">ylab =</span> <span class="kw">expression</span>(<span class="kw">S</span>(t))</a>
<a class="sourceLine" id="cb59-9" title="9">)</a>
<a class="sourceLine" id="cb59-10" title="10"><span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="dt">legend =</span> <span class="kw">levels</span>(ipec<span class="op">$</span>escola), <span class="dt">fill =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>)</a></code></pre></div>
<p><img src="exercicio-cap-4_files/figure-html/unnamed-chunk-21-2.png" width="672" /></p>
<p>A análise do gráfico da sobrevivência aponta diferenças na escolaridade, porém, as curvas estão bastante próximas uma das outras, o que sugere que, se há diferenças na sobrevivência entre os níveis de escolaridade, estas diferenças não são facilmente captadas num banco de dados deste tamanho, já que ocorrerá bastante sobreposição nos intervalos de confiança. O gráfico de risco mostra algo semelhante, já que o risco para os diferentes níveis de escolaridade não se diferenciam significativamente uns dos outros ao longo do acompanhamento. Vejamos,</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1">esc_lr &lt;-<span class="st"> </span><span class="kw">survdiff</span>(<span class="kw">Surv</span>(tempo, status) <span class="op">~</span><span class="st"> </span>escola, <span class="dt">data =</span> ipec)</a>
<a class="sourceLine" id="cb60-2" title="2">esc_pt &lt;-<span class="st"> </span><span class="kw">survdiff</span>(<span class="kw">Surv</span>(tempo, status) <span class="op">~</span><span class="st"> </span>escola, <span class="dt">data =</span> ipec, <span class="dt">rho =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb60-3" title="3">esc_lr</a></code></pre></div>
<pre><code>## Call:
## survdiff(formula = Surv(tempo, status) ~ escola, data = ipec)
## 
## n=182, 11 observations deleted due to missingness.
## 
##                N Observed Expected (O-E)^2/E (O-E)^2/V
## escola=sem    59       26     24.2    0.1348    0.1910
## escola=fundam 44       20     19.2    0.0376    0.0490
## escola=medio  55       27     30.4    0.3785    0.6111
## escola=sup    24       11     10.3    0.0529    0.0605
## 
##  Chisq= 0.6  on 3 degrees of freedom, p= 0.9</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" title="1">esc_pt</a></code></pre></div>
<pre><code>## Call:
## survdiff(formula = Surv(tempo, status) ~ escola, data = ipec, 
##     rho = 1)
## 
## n=182, 11 observations deleted due to missingness.
## 
##                N Observed Expected (O-E)^2/E (O-E)^2/V
## escola=sem    59    20.50    18.55    0.2048    0.3683
## escola=fundam 44    15.96    14.56    0.1348    0.2228
## escola=medio  55    18.42    22.10    0.6112    1.2316
## escola=sup    24     8.16     7.84    0.0135    0.0195
## 
##  Chisq= 1.3  on 3 degrees of freedom, p= 0.7</code></pre>
<p>Realmente, apesar das diferenças observadas, os <span class="math inline">\(p\)</span>-valores não são suficientes para rejeitar a hipótese nula, seja no teste de log-rank, seja no Peto, já que existe grande probabilidade deste resultado ser produto de uma amostra não representativa da população.</p>
<p>Se analisamos os quantis,</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" title="1"><span class="kw">quantile</span>(escola, <span class="dt">probs =</span> <span class="kw">c</span>(<span class="fl">0.1</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>))</a></code></pre></div>
<pre><code>## $quantile
##                10  25   50
## escola=sem    116 310 1371
## escola=fundam  84 333 1116
## escola=medio  214 688 1563
## escola=sup    204 623  855
## 
## $lower
##                10  25   50
## escola=sem     52 173  850
## escola=fundam  22 152  733
## escola=medio  123 371 1085
## escola=sup     21 204  644
## 
## $upper
##                10   25 50
## escola=sem    285  887 NA
## escola=fundam 333  944 NA
## escola=medio  618 1125 NA
## escola=sup    811 1261 NA</code></pre>
<p>Notamos que os intervalos de confiança apresentam bastante sobreposição. No caso do quantil 0.1, por exemplo, as pessoas sem escolaridade tem sobrevivência de 50% daquelas com ensino médio se consideramos a estimativa pontual (116 &lt; 214), porém, quando analisamos os intervalos de confiança (respectivamente, [52, 285], [123, 618]), vemos que esta diferença não é mais tão clara quanto, por exemplo, no caso dos diferentes tipos de tratamento.</p>
</div>
<div id="síntese" class="section level4">
<h4>Síntese</h4>
<p>Em suma, as análises mostraram que o tratamento foi uma covariável importante para a sobrevivência, estatisticamente robusta e, em menor medida, o sexo também pode ser considerado uma covariável significativa. A educação, embora apesar de conhecida sua relevância para a questão da saúde da população, não apresenta informações suficientes neste banco de dados para fazer afirmações estatisticamente robustas sobre a sua associação com a sobrevivência.</p>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
